#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Paper-oriented exports and figure generation utilities.

The functions in this module are intentionally read-only with respect to model
training. They save test-set predictions, ingredient-attention case tables, and
paper figures from files generated by a completed run.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
from typing import Any, Dict, Iterable, List, Optional, Sequence

import numpy as np
import pandas as pd

try:
    import torch
except Exception:  # plotting from exported CSV/JSON does not require torch
    torch = None

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:  # pragma: no cover
    plt = None


def _torch_no_grad(func):
    if torch is None:
        return func
    return torch.no_grad()(func)


def _ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def _as_numpy(values: Any, dtype=None) -> np.ndarray:
    if values is None:
        return np.array([], dtype=dtype)
    if torch is not None and isinstance(values, torch.Tensor):
        arr = values.detach().cpu().numpy()
    else:
        arr = np.asarray(values)
    if dtype is not None:
        arr = arr.astype(dtype)
    return arr


def _safe_float(value: Any) -> float:
    try:
        return float(value)
    except Exception:
        return float("nan")


def _load_name_mapping(path: Optional[str]) -> Dict[str, Any]:
    if not path or not os.path.exists(path):
        return {}
    try:
        from utils import load_id_name_mapping
        return load_id_name_mapping(path)
    except Exception:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)


def _lookup_name(mapping: Dict[str, Any], node_type: str, idx: int) -> str:
    section = mapping.get(node_type, {}) if isinstance(mapping, dict) else {}
    if not isinstance(section, dict):
        return f"{node_type}_{idx}"
    index_to_name = section.get("index_to_name") or section.get("index2name")
    if isinstance(index_to_name, dict):
        return str(index_to_name.get(str(idx), index_to_name.get(idx, f"{node_type}_{idx}")))
    return str(section.get(str(idx), section.get(idx, f"{node_type}_{idx}")))


def save_test_predictions_csv(
    save_path: str,
    herb_ids: Sequence[int],
    target_ids: Sequence[int],
    labels: Sequence[float],
    probs: Sequence[float],
    logits: Optional[Sequence[float]] = None,
    threshold: Optional[float] = None,
    id_name_mapping_path: Optional[str] = None,
) -> str:
    """Save sample-level test predictions for paper diagnostics."""
    _ensure_dir(os.path.dirname(save_path) or ".")
    mapping = _load_name_mapping(id_name_mapping_path)

    herb_arr = _as_numpy(herb_ids, dtype=int)
    target_arr = _as_numpy(target_ids, dtype=int)
    label_arr = _as_numpy(labels, dtype=float)
    prob_arr = _as_numpy(probs, dtype=float)
    logit_arr = _as_numpy(logits, dtype=float) if logits is not None else np.full_like(prob_arr, np.nan)

    n = min(len(herb_arr), len(target_arr), len(label_arr), len(prob_arr), len(logit_arr))
    thr = float(threshold) if threshold is not None else 0.5

    with open(save_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "sample_index",
                "herb_id",
                "herb_name",
                "target_id",
                "target_name",
                "label",
                "probability",
                "logit",
                "predicted_label",
            ],
        )
        writer.writeheader()
        for i in range(n):
            h = int(herb_arr[i])
            t = int(target_arr[i])
            p = float(prob_arr[i])
            writer.writerow({
                "sample_index": i,
                "herb_id": h,
                "herb_name": _lookup_name(mapping, "herb", h),
                "target_id": t,
                "target_name": _lookup_name(mapping, "target", t),
                "label": int(label_arr[i] >= 0.5),
                "probability": p,
                "logit": _safe_float(logit_arr[i]),
                "predicted_label": int(p >= thr),
            })
    return save_path


@_torch_no_grad
def export_attention_case_csv(
    model,
    msg_graph,
    herb_to_ings: Dict[int, List[int]],
    herb_ids: Sequence[int],
    target_ids: Sequence[int],
    labels: Sequence[float],
    probs: Sequence[float],
    save_path: str,
    device: torch.device,
    top_cases: int = 3,
    top_ingredients: int = 12,
    id_name_mapping_path: Optional[str] = None,
) -> str:
    """Export ingredient-attention case records for interpretability figures."""
    if torch is None:
        raise RuntimeError("PyTorch is required to export attention case records.")
    from cold_start_split import build_herb_ing_padded

    _ensure_dir(os.path.dirname(save_path) or ".")
    mapping = _load_name_mapping(id_name_mapping_path)

    herb_arr = _as_numpy(herb_ids, dtype=int)
    target_arr = _as_numpy(target_ids, dtype=int)
    label_arr = _as_numpy(labels, dtype=float)
    prob_arr = _as_numpy(probs, dtype=float)
    n = min(len(herb_arr), len(target_arr), len(label_arr), len(prob_arr))
    if n == 0:
        return save_path

    positive_idx = np.where(label_arr[:n] >= 0.5)[0]
    candidate_idx = positive_idx if positive_idx.size else np.arange(n)
    candidate_idx = candidate_idx[np.argsort(-prob_arr[candidate_idx])]
    candidate_idx = candidate_idx[: max(1, int(top_cases))]

    rows: List[Dict[str, Any]] = []
    model.eval()
    msg_graph = msg_graph.to(device)

    for case_rank, sample_idx in enumerate(candidate_idx, start=1):
        h = int(herb_arr[sample_idx])
        t = int(target_arr[sample_idx])
        h_tensor = torch.tensor([h], dtype=torch.long, device=device)
        t_tensor = torch.tensor([t], dtype=torch.long, device=device)
        padded, mask = build_herb_ing_padded(h_tensor.detach().cpu(), herb_to_ings)
        padded = padded.to(device)
        mask = mask.to(device)

        out = model(
            msg_graph,
            h_tensor,
            t_tensor,
            padded,
            mask,
            return_attention=True,
            return_aux=True,
        )
        if not isinstance(out, tuple) or len(out) != 3:
            continue
        score_tensor, attn_tensor, aux = out
        score = float(score_tensor.detach().cpu().view(-1)[0])
        attention = attn_tensor.detach().cpu().view(-1).numpy()
        valid_mask = mask.detach().cpu().view(-1).numpy().astype(bool)
        compat = None
        if isinstance(aux, dict) and "compat_scores" in aux:
            compat = aux["compat_scores"].detach().cpu().view(-1).numpy()
        ingredient_score = _safe_float(aux.get("ingredient_score", [np.nan])[0] if isinstance(aux, dict) and "ingredient_score" in aux else np.nan)
        global_score = _safe_float(aux.get("global_score", [np.nan])[0] if isinstance(aux, dict) and "global_score" in aux else np.nan)
        lambda_global = _safe_float(aux.get("lambda_global", np.nan) if isinstance(aux, dict) else np.nan)

        ing_list = list(herb_to_ings.get(h, []))
        records = []
        for pos, ing_id in enumerate(ing_list):
            if pos >= len(attention) or pos >= len(valid_mask) or not valid_mask[pos]:
                continue
            comp_value = float(compat[pos]) if compat is not None and pos < len(compat) else float("nan")
            attn_value = float(attention[pos])
            records.append({
                "position": pos,
                "ingredient_id": int(ing_id),
                "attention": attn_value,
                "compatibility_logit": comp_value,
                "attention_x_compatibility": attn_value * comp_value if np.isfinite(comp_value) else float("nan"),
            })
        records.sort(key=lambda item: item["attention"], reverse=True)
        total_attention = sum(max(0.0, item["attention"]) for item in records) or 1.0

        for ingredient_rank, item in enumerate(records[: max(1, int(top_ingredients))], start=1):
            iid = int(item["ingredient_id"])
            rows.append({
                "case_rank": case_rank,
                "sample_index": int(sample_idx),
                "herb_id": h,
                "herb_name": _lookup_name(mapping, "herb", h),
                "target_id": t,
                "target_name": _lookup_name(mapping, "target", t),
                "label": int(label_arr[sample_idx] >= 0.5),
                "probability": float(prob_arr[sample_idx]),
                "model_logit": score,
                "ingredient_score": ingredient_score,
                "global_score": global_score,
                "lambda_global": lambda_global,
                "ingredient_rank": ingredient_rank,
                "ingredient_id": iid,
                "ingredient_name": _lookup_name(mapping, "ingredient", iid),
                "attention": float(item["attention"]),
                "attention_share": float(max(0.0, item["attention"]) / total_attention),
                "compatibility_logit": float(item["compatibility_logit"]),
                "attention_x_compatibility": float(item["attention_x_compatibility"]),
            })

    columns = [
        "case_rank", "sample_index", "herb_id", "herb_name", "target_id", "target_name",
        "label", "probability", "model_logit", "ingredient_score", "global_score",
        "lambda_global", "ingredient_rank", "ingredient_id", "ingredient_name",
        "attention", "attention_share", "compatibility_logit", "attention_x_compatibility",
    ]
    with open(save_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)
    return save_path


def _apply_paper_style() -> None:
    if plt is None:
        raise RuntimeError("matplotlib is required for plotting")
    plt.rcParams.update({
        "figure.dpi": 160,
        "savefig.dpi": 600,
        "font.family": "DejaVu Sans",
        "font.size": 8.5,
        "axes.titlesize": 9.5,
        "axes.labelsize": 8.5,
        "legend.fontsize": 7.5,
        "xtick.labelsize": 7.5,
        "ytick.labelsize": 7.5,
        "axes.linewidth": 0.8,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def _save_figure(fig, out_dir: str, name: str) -> None:
    _ensure_dir(out_dir)
    for ext in ("png", "pdf", "svg"):
        fig.savefig(os.path.join(out_dir, f"{name}.{ext}"), bbox_inches="tight")
    plt.close(fig)


def _read_curve_payloads(run_dir: str) -> List[Dict[str, Any]]:
    paths = sorted(glob.glob(os.path.join(run_dir, "*_curves.json")))
    payloads = []
    for path in paths:
        try:
            with open(path, "r", encoding="utf-8") as f:
                payload = json.load(f)
            payload["name"] = os.path.basename(path).replace("_curves.json", "")
            payloads.append(payload)
        except Exception:
            continue
    return payloads


def plot_roc_pr_curves(run_dir: str, out_dir: str) -> Optional[str]:
    payloads = _read_curve_payloads(run_dir)
    payloads = [p for p in payloads if {"fpr", "tpr", "precision", "recall"}.issubset(p.keys())]
    if not payloads:
        return None
    _apply_paper_style()
    colors = ["#1F77B4", "#D62728", "#2CA02C", "#9467BD", "#8C564B"]
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0))
    for i, payload in enumerate(payloads):
        label = str(payload.get("name", f"model_{i+1}"))
        color = colors[i % len(colors)]
        auc_value = payload.get("auc", payload.get("AUC", np.nan))
        auprc_value = payload.get("auprc", payload.get("AUPRC", np.nan))
        axes[0].plot(payload["fpr"], payload["tpr"], lw=1.6, color=color, label=f"{label} (AUC={float(auc_value):.4f})")
        axes[1].plot(payload["recall"], payload["precision"], lw=1.6, color=color, label=f"{label} (AUPRC={float(auprc_value):.4f})")
    axes[0].plot([0, 1], [0, 1], ls="--", lw=0.8, color="#8A8A8A")
    axes[0].set_xlabel("False positive rate")
    axes[0].set_ylabel("True positive rate")
    axes[0].set_title("ROC curve")
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].set_title("Precision-recall curve")
    for ax in axes:
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.legend(frameon=False, loc="lower right" if ax is axes[0] else "lower left")
    fig.tight_layout(w_pad=1.8)
    _save_figure(fig, out_dir, "Figure_ROC_PR_curves")
    return os.path.join(out_dir, "Figure_ROC_PR_curves.pdf")


def plot_rl_dynamics(run_dir: str, out_dir: str) -> Optional[str]:
    path = os.path.join(run_dir, "rl_dynamics_log.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    if df.empty or "epoch" not in df.columns:
        return None
    _apply_paper_style()
    fig, axes = plt.subplots(2, 2, figsize=(7.2, 5.2))
    ax = axes[0, 0]
    for col, color, label in [("val_auc", "#1F77B4", "Validation AUC"), ("val_f1", "#D62728", "Validation F1")]:
        if col in df.columns:
            ax.plot(df["epoch"], df[col], marker="o", ms=2.5, lw=1.2, color=color, label=label)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Score")
    ax.set_title("Validation response after topology actions")
    ax.legend(frameon=False)

    ax = axes[0, 1]
    density_cols = [c for c in ["hh_density", "ii_density", "tt_density"] if c in df.columns]
    for col, color in zip(density_cols, ["#2CA02C", "#9467BD", "#FF7F0E"]):
        ax.plot(df["epoch"], df[col], marker="o", ms=2.5, lw=1.2, color=color, label=col.replace("_", " "))
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Virtual-edge density")
    ax.set_title("Adaptive graph sparsity")
    ax.legend(frameon=False)

    ax = axes[1, 0]
    if "threshold" in df.columns:
        ax.plot(df["epoch"], df["threshold"], marker="o", ms=2.5, lw=1.2, color="#1F77B4", label="Threshold")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Similarity threshold")
    if "topk" in df.columns:
        ax2 = ax.twinx()
        ax2.plot(df["epoch"], df["topk"], marker="s", ms=2.5, lw=1.0, color="#D62728", label="Top-k")
        ax2.set_ylabel("Top-k")
        lines, labels = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines + lines2, labels + labels2, frameon=False, loc="best")
    else:
        ax.legend(frameon=False)
    ax.set_title("Topology-control parameters")

    ax = axes[1, 1]
    if "rl_reward" in df.columns:
        ax.axhline(0, lw=0.8, color="#9A9A9A", ls="--")
        ax.plot(df["epoch"], df["rl_reward"], marker="o", ms=2.5, lw=1.2, color="#2CA02C", label="Reward")
    if "epsilon" in df.columns:
        ax2 = ax.twinx()
        ax2.plot(df["epoch"], df["epsilon"], marker="s", ms=2.5, lw=1.0, color="#9467BD", label="Epsilon")
        ax2.set_ylabel("Exploration rate")
        lines, labels = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines + lines2, labels + labels2, frameon=False, loc="best")
    else:
        ax.legend(frameon=False)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Reward")
    ax.set_title("Policy feedback")

    for ax in axes.ravel():
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    fig.tight_layout(w_pad=1.8, h_pad=2.0)
    _save_figure(fig, out_dir, "Figure_RL_dynamics")
    return os.path.join(out_dir, "Figure_RL_dynamics.pdf")


def _latest_matching(run_dir: str, suffix: str) -> Optional[str]:
    paths = sorted(glob.glob(os.path.join(run_dir, f"*{suffix}")), key=os.path.getmtime)
    return paths[-1] if paths else None


def plot_score_distribution(run_dir: str, out_dir: str) -> Optional[str]:
    path = _latest_matching(run_dir, "_test_predictions.csv")
    if path is None:
        return None
    df = pd.read_csv(path)
    if df.empty or "probability" not in df.columns or "label" not in df.columns:
        return None
    _apply_paper_style()
    fig, ax = plt.subplots(figsize=(3.5, 2.8))
    bins = np.linspace(0.0, 1.0, 31)
    pos = df.loc[df["label"] >= 0.5, "probability"].astype(float).to_numpy()
    neg = df.loc[df["label"] < 0.5, "probability"].astype(float).to_numpy()
    ax.hist(neg, bins=bins, density=True, alpha=0.55, color="#7F8C8D", label="Negative")
    ax.hist(pos, bins=bins, density=True, alpha=0.55, color="#D62728", label="Positive")
    ax.set_xlabel("Predicted probability")
    ax.set_ylabel("Density")
    ax.set_title("Score distribution on the test set")
    ax.legend(frameon=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    _save_figure(fig, out_dir, "Figure_score_distribution")
    return os.path.join(out_dir, "Figure_score_distribution.pdf")


def plot_attention_case(run_dir: str, out_dir: str) -> Optional[str]:
    path = _latest_matching(run_dir, "_explanation_cases.csv")
    if path is None:
        return None
    df = pd.read_csv(path)
    if df.empty or "attention" not in df.columns:
        return None
    case_id = df["case_rank"].min() if "case_rank" in df.columns else 1
    case_df = df[df["case_rank"] == case_id].copy() if "case_rank" in df.columns else df.copy()
    case_df = case_df.sort_values("attention", ascending=True)
    _apply_paper_style()
    fig, ax = plt.subplots(figsize=(4.0, max(2.6, 0.28 * len(case_df) + 0.8)))
    values = case_df["attention"].astype(float).to_numpy()
    labels = case_df.get("ingredient_name", case_df.get("ingredient_id", pd.Series(range(len(case_df))))).astype(str).str.slice(0, 36).tolist()
    colors = plt.cm.YlGnBu(np.linspace(0.45, 0.85, len(case_df)))
    ax.barh(np.arange(len(case_df)), values, color=colors, edgecolor="white", lw=0.4)
    ax.set_yticks(np.arange(len(case_df)))
    ax.set_yticklabels(labels)
    ax.set_xlabel("Ingredient attention weight")
    herb_name = str(case_df["herb_name"].iloc[0]) if "herb_name" in case_df.columns else "Herb"
    target_name = str(case_df["target_name"].iloc[0]) if "target_name" in case_df.columns else "Target"
    probability = float(case_df["probability"].iloc[0]) if "probability" in case_df.columns else float("nan")
    ax.set_title(f"Ingredient evidence profile: {herb_name} -> {target_name} (P={probability:.3f})")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    _save_figure(fig, out_dir, "Figure_ingredient_evidence_case")
    return os.path.join(out_dir, "Figure_ingredient_evidence_case.pdf")


DEFAULT_RUN_DIR = "checkpoints"


def _has_figure_inputs(run_dir: str) -> bool:
    return bool(
        glob.glob(os.path.join(run_dir, "*_curves.json"))
        or os.path.exists(os.path.join(run_dir, "rl_dynamics_log.csv"))
        or _latest_matching(run_dir, "_test_predictions.csv")
        or _latest_matching(run_dir, "_explanation_cases.csv")
    )


def _candidate_run_score(run_dir: str) -> tuple:
    input_patterns = [
        "*_curves.json",
        "rl_dynamics_log.csv",
        "*_test_predictions.csv",
        "*_explanation_cases.csv",
    ]
    paths: List[str] = []
    for pattern in input_patterns:
        paths.extend(glob.glob(os.path.join(run_dir, pattern)))
    latest_mtime = max((os.path.getmtime(path) for path in paths), default=0.0)
    normalized_parts = {part.lower() for part in os.path.normpath(run_dir).split(os.sep)}
    preferred_model = int(bool(normalized_parts & {"proposed_model", "full_model", "a4_full_model"}))
    aggregate_run = int(not any(part.startswith("seed_") for part in normalized_parts))
    return (preferred_model, aggregate_run, len(paths), latest_mtime, run_dir)


def _auto_select_run_dir(root_dir: str = DEFAULT_RUN_DIR) -> str:
    if _has_figure_inputs(root_dir):
        return root_dir

    candidates = set()
    input_patterns = [
        "*_curves.json",
        "rl_dynamics_log.csv",
        "*_test_predictions.csv",
        "*_explanation_cases.csv",
    ]
    for pattern in input_patterns:
        for path in glob.glob(os.path.join(root_dir, "**", pattern), recursive=True):
            candidates.add(os.path.dirname(path))

    if not candidates:
        return root_dir
    return max(candidates, key=_candidate_run_score)


def generate_paper_figures(run_dir: str, out_dir: Optional[str] = None) -> Dict[str, Optional[str]]:
    if out_dir is None:
        out_dir = os.path.join(run_dir, "paper_figures")
    outputs = {
        "roc_pr_curves": plot_roc_pr_curves(run_dir, out_dir),
        "rl_dynamics": plot_rl_dynamics(run_dir, out_dir),
        "score_distribution": plot_score_distribution(run_dir, out_dir),
        "ingredient_evidence_case": plot_attention_case(run_dir, out_dir),
    }
    manifest_path = os.path.join(out_dir, "paper_figure_manifest.json")
    _ensure_dir(out_dir)
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(outputs, f, ensure_ascii=False, indent=2)
    outputs["manifest"] = manifest_path
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate paper figures from a completed run directory.")
    parser.add_argument("--run-dir", default=None, help="Directory containing curves, RL log, and exported CSV files. Defaults to auto-search under checkpoints.")
    parser.add_argument("--out-dir", default=None, help="Output directory for figures. Defaults to checkpoints/paper_figures in auto mode, otherwise <run-dir>/paper_figures.")
    args = parser.parse_args()

    auto_mode = args.run_dir is None
    requested_run_dir = DEFAULT_RUN_DIR if auto_mode else args.run_dir
    run_dir = requested_run_dir
    if not _has_figure_inputs(run_dir):
        run_dir = _auto_select_run_dir(run_dir)

    out_dir = args.out_dir
    if out_dir is None and auto_mode:
        out_dir = os.path.join(DEFAULT_RUN_DIR, "paper_figures")

    if run_dir != requested_run_dir:
        print(f"Auto-selected run directory: {run_dir}")
        print(f"Output directory: {out_dir or os.path.join(run_dir, 'paper_figures')}")

    outputs = generate_paper_figures(run_dir, out_dir)
    print(json.dumps(outputs, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
